### ISSUE TITLE
Error using Cifar-10

### ISSUE THREAD

**Issue by ksk0629** [ksk0629/quanvolutional_neural_network#34]
# What to do
Resolve the error that occurs when using the Cifar-10 dataset. Remark that the script mentioned in the error message hasn't been pushed.

```
(quanvolutional_neural_network) (base) ksk@Keisukes-MacBook-Air quanvolutional_neural_network % python ./scripts/train_model_with_cifar10.py -c configs/cifar10_quanv_nn.yaml
Files already downloaded and verified
Files already downloaded and verified
The number of train dataset: 50000
The number of test dataset: 10000
2024/09/11 13:28:08 INFO mlflow.tracking.fluent: Experiment with name 'cifar10' does not exist. Creating a new experiment.
Dataset: 100%|█████████████████████████████████████████████████| 50000/50000 [13:33<00:00, 61.43it/s]
Dataset: 100%|█████████████████████████████████████████████████| 10000/10000 [02:41<00:00, 61.87it/s]
  0%|                                                                        | 0/586 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/ksk/dev/github/quanvolutional_neural_network/./scripts/train_model_with_cifar10.py", line 34, in <module>
    train(
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/train_model.py", line 177, in train
    trainer.train_and_test()
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/quanv_nn_trainer.py", line 125, in train_and_test
    self.trainer.train_and_test()
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/trainer.py", line 220, in train_and_test
    self.train_and_test_one_epoch()
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/trainer.py", line 213, in train_and_test_one_epoch
    self.train()
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/trainer.py", line 127, in train
    for data, label in tepoch:
                       ^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/quanvolutional_neural_network/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/quanvolutional_neural_network/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/quanvolutional_neural_network/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/quanvolutional_neural_network/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/ksk/dev/github/quanvolutional_neural_network/src/plain_dataset.py", line 20, in __getitem__
    return self.x[idx], self.y[idx]
                        ~~~~~~^^^^^
IndexError: index 75105 is out of bounds for dimension 0 with size 50000
```

**Comment by ksk0629** [comment]
I speculate that the error happened because of the gaps between the number of labels and processed data.

**Comment by ksk0629** [comment]
It did so. Each channel of the data was treated as individual data, so the processed dataset has a shape [original batch size * number of channels, number of filters, original height, original width].
